### ISSUE TITLE
auth.json

### ISSUE THREAD

**Issue by whitebook** [uhppoted/httpd#1]
Not sure where to locate a sample auth.json or what command to run to create this file...

**Comment by uhppoted** [comment]
Hi,

This subproject is in **very** early stage development - didn't think anybody was actually looking at it. 

Have added some working `auth`, `rules` and _data_ files to the [_documentation_](https://github.com/uhppoted/httpd/tree/master/documentation) folder.

**Comment by whitebook** [comment]
Thanks. I will check your recent commits. I am very interested in this project. I see its early stage. I am not worried about any major breaking changes.  

Thanks.
